### ISSUE TITLE
Nedostatak makroa

### ISSUE THREAD

**Issue by nikolabebic95** [vomindoraan/P2-Rokovi#1]
Možeš da rešiš problem zbog koga makro ne smeš da stavljaš u mali if tako što celo telo makroa ubaciš u do { ... } while (0), gde su tri tačke telo makroa koje sada imaš.

Na primer, makro ASSIGN bi izgledao ovako:
#define ASSIGN(p, f, m) do { if (!((p) = fopen(f, m))) perror(f), exit(1) } while (0)

**Comment by vomindoraan** [comment]
Знам за то, али ми се чини да је то сувишно овде. Биће проблем људима да скапирају — већ је довољно сложено тако како јесте. Уосталом, довољно је ставити витичасте заграде у мали `if` и радиће како треба. Или ставити само заграде у макро (али тада мора да се изостави `;` на крају, то ми се не свиђа толико).

Хвала на предлогу у сваком случају 😀
